import type { Metadata } from "next";
import { Montserrat } from "next/font/google"; 2 
import {Header} from "@/widgets/Header/ui/Header"
import "./globals.css";
 
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-montserrat",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   return (
    <html lang="en" className={`${montserrat.variable}`}>
      <body>  
         <Header/>
        {children} 
         </body> 
    </html>
  );

}
