import doctorImage from "@/shared/assets/img/Doc/docer.png";
import type { Doctor } from "./types"; 
export const doctors: Doctor[] = [
  {
    id: 1,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 2,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 3,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 4,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 5,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 6,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 7,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 8,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
  {
    id: 9,
    name: "Кадыржакунов Нурлан",
    specialization: "Хирург",
    experience: "опыт 14 лет",
    rating: 4.9,
    image: doctorImage,
  },
];